# Generator script part 2 - HTML content
import os

outpath = os.path.join(os.path.dirname(os.path.abspath(__file__)), "gateway.py")

html_lines = []
def h(s=""):
    html_lines.append(s)

h('# ---------------------------------------------------------------------------')
h('# HTML Panel')
h('# ---------------------------------------------------------------------------')
h()
h('HTML = r\'\'\''' + "'" + '''<!DOCTYPE html>''')
h('''<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">''')
h('''<title>BYO-OS Panel</title>''')
h('''<style>''')
h('''*{margin:0;padding:0;box-sizing:border-box}''')
h('''body{font-family:system-ui,-apple-system,sans-serif;background:#0a0e1a;color:#e2e8f0;min-height:100vh}''')
h('''#sb{position:fixed;width:210px;height:100%;background:#111827;border-right:1px solid #1e293b;display:flex;flex-direction:column;z-index:100}''')
h('''#sb .logo{padding:18px;text-align:center;border-bottom:1px solid #1e293b}''')
h('''#sb .logo h1{color:#38bdf8;font-size:17px;letter-spacing:1px}''')
h('''#sb .logo p{color:#64748b;font-size:10px;margin-top:3px}''')
h('''#sb nav{flex:1;overflow-y:auto;padding:8px 0}''')
h('''#sb nav a{display:flex;align-items:center;gap:8px;padding:9px 16px;color:#94a3b8;text-decoration:none;font-size:13px;border-left:3px solid transparent;transition:all .15s}''')
h('''#sb nav a:hover{background:#1e293b;color:#e2e8f0}''')
h('''#sb nav a.on{color:#38bdf8;background:rgba(56,189,248,.08);border-left-color:#38bdf8}''')
h('''#sb nav .sep{padding:4px 16px;font-size:10px;color:#475569;text-transform:uppercase;letter-spacing:1px;margin-top:8px}''')
h('''#sb .ft{padding:10px 16px;border-top:1px solid #1e293b;font-size:10px;color:#475569}''')
h('''#mn{margin-left:210px;padding:20px}''')
h('''.pg{display:none}.pg.on{display:block}''')
h('''h2{font-size:18px;margin-bottom:14px;font-weight:600}''')
h('''.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px;margin-bottom:16px}''')
h('''.card{background:#111827;border-radius:10px;padding:14px;border:1px solid #1e293b}''')
h('''.card h3{color:#64748b;font-size:11px;text-transform:uppercase;margin-bottom:8px;letter-spacing:.5px}''')
h('''.big{font-size:24px;font-weight:700}''')
h('''.row{display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #1e293b;font-size:12px}''')
h('''.row:last-child{border:none}''')
h('''.lbl{color:#64748b}.val{color:#e2e8f0;font-weight:500}''')
h('''.bar{background:#1e293b;border-radius:3px;height:5px;margin:6px 0}''')
h('''.fill{height:100%;border-radius:3px;background:linear-gradient(90deg,#22c55e,#16a34a);transition:width .5s}''')
h('''.fill.y{background:linear-gradient(90deg,#eab308,#ca8a04)}''')
h('''.fill.r{background:linear-gradient(90deg,#ef4444,#dc2626)}''')
h('''.g{color:#22c55e}.y{color:#eab308}.r{color:#ef4444}.b{color:#38bdf8}.dim{color:#64748b}''')
h('''table{width:100%;border-collapse:collapse;font-size:12px}''')
h('''th{text-align:left;padding:8px;color:#64748b;border-bottom:2px solid #1e293b;font-size:11px;text-transform:uppercase}''')
h('''td{padding:7px 8px;border-bottom:1px solid #1e293b}''')
h('''tr:hover td{background:rgba(56,189,248,.03)}''')
h('''.btn{padding:5px 12px;border-radius:5px;border:none;cursor:pointer;font-size:11px;font-weight:600;transition:all .15s}''')
h('''.bp{background:#38bdf8;color:#0f172a}.bp:hover{background:#0ea5e9}''')
h('''.bd{background:#ef4444;color:#fff}.bd:hover{background:#dc2626}''')
h('''.bg{background:#22c55e;color:#fff}.bg:hover{background:#16a34a}''')
h('''.bk{background:#1e293b;color:#e2e8f0;border:1px solid #334155}.bk:hover{background:#334155}''')
h('''.term{background:#0c0c0c;border-radius:8px;padding:12px;font-family:'Cascadia Code','Fira Code',monospace;font-size:12px;height:400px;overflow-y:auto;border:1px solid #1e293b;scroll-behavior:smooth}''')
h('''.ti{display:flex;gap:6px;margin-top:8px}''')
h('''.ti input{flex:1;background:#0c0c0c;border:1px solid #1e293b;color:#e2e8f0;padding:8px 12px;border-radius:6px;font-family:inherit;font-size:13px;outline:none}''')
h('''.ti input:focus{border-color:#38bdf8}''')
h('''.ti button{padding:8px 16px;background:#38bdf8;color:#0f172a;border:none;border-radius:6px;font-weight:600;cursor:pointer;font-size:13px}''')
h('''.ti button:hover{background:#0ea5e9}''')
h('''.c1{color:#38bdf8;font-weight:600}.c2{color:#e2e8f0}.c3{color:#ef4444}.c4{color:#22c55e}.c5{color:#eab308}''')
h('''.bdg{display:inline-block;padding:2px 8px;border-radius:4px;font-size:10px;font-weight:700;background:#22c55e;color:#000;margin-left:8px;vertical-align:middle}''')
h('''.bdg.off{background:#ef4444}''')
h('''.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#22c55e;margin-right:4px;vertical-align:middle;animation:pulse 2s infinite}''')
h('''@keyframes pulse{0%,100%{opacity:1}50%{opacity:.4}}''')
h('''.badge{display:inline-block;padding:1px 6px;border-radius:3px;font-size:9px;font-weight:600}''')
h('''.badge.ok{background:#16a34a;color:#fff}''')
h('''.badge.off{background:#64748b;color:#fff}''')
h('''.mt{margin-top:10px}.mb{margin-bottom:10px}''')
h('''pre{font-family:'Cascadia Code','Fira Code',monospace;white-space:pre-wrap;word-break:break-all;font-size:12px;line-height:1.5;color:#e2e8f0;margin:0}''')
h('''.toast{position:fixed;bottom:20px;right:20px;background:#1e293b;border:1px solid #334155;border-radius:8px;padding:10px 16px;font-size:12px;color:#e2e8f0;z-index:999;opacity:0;transition:opacity .3s}''')
h('''.toast.show{opacity:1}''')
h('''.toast.err{border-color:#ef4444;color:#ef4444}''')
h('''.fview{background:#0c0c0c;border-radius:8px;padding:12px;max-height:500px;overflow:auto;border:1px solid #1e293b}''')
h('''.fview pre{margin:0}''')
h('''</style>''')
h('''</head><body>''')

# Sidebar navigation
h('''<div id="sb">''')
h('''<div class="logo"><h1>BYO-OS</h1><p>v0.2 Beta Panel</p></div>''')
h('''<nav>''')
h('''<a href="#" class="on" onclick="go('dash',this);return false">&#9632; Dashboard</a>''')
h('''<a href="#" onclick="go('term',this);return false">&#9654; Terminal</a>''')
h('''<div class="sep">System</div>''')
h('''<a href="#" onclick="go('proc',this);return false">&#9881; Processes</a>''')
h('''<a href="#" onclick="go('mon',this);return false">&#9734; Monitor</a>''')
h('''<a href="#" onclick="go('file',this);return false">&#128193; File Manager</a>''')
h('''<a href="#" onclick="go('log',this);return false">&#9998; System Logs</a>''')
h('''<div class="sep">Network</div>''')
h('''<a href="#" onclick="go('net',this);return false">&#9729; Network Config</a>''')
h('''<a href="#" onclick="go('netmon',this);return false">&#9879; Connections</a>''')
h('''<div class="sep">Admin</div>''')
h('''<a href="#" onclick="go('user',this);return false">&#9775; Users</a>''')
h('''<a href="#" onclick="go('svc',this);return false">&#9881; Services</a>''')
h('''<a href="#" onclick="go('cron',this);return false">&#9200; Scheduler</a>''')
h('''<div class="sep">Tools</div>''')
h('''<a href="#" onclick="go('pkg',this);return false">&#128230; Packages</a>''')
h('''<a href="#" onclick="go('backup',this);return false">&#9878; Backup</a>''')
h('''<a href="#" onclick="go('set',this);return false">&#9881; Settings</a>''')
h('''</nav>''')
h('''<div class="ft" id="sfoot">Serial: checking...</div>''')
h('''</div>''')
h()
h('''<div id="mn">''')

content2 = "\n".join(html_lines)

# Read existing partial file
with open(outpath, "r", encoding="utf-8") as f:
    existing = f.read()

with open(outpath, "a", encoding="utf-8", newline="\n") as f:
    f.write(content2)

print(f"Part 2 written: {len(content2)} chars")
