import os
# Build shell.c content
content = ""
# Read each section from separate text and combine

# We'll write directly
with open('E:/aisystem/byo-os/kernel/shell.c', 'w', encoding='utf-8', newline='\n') as f:
    f.write("/* BYO-OS Shell v3.0 - Generated */\n")
    f.write("#include <kernel.h>\n\n")
    f.write("#define CMD_BUF_SIZE 256\n")
    f.write("static char cmd_buffer[CMD_BUF_SIZE];\n")
    f.write("static int cmd_pos = 0;\n")
    f.write("static int serial_processed = 0;\n\n")
    f.write("#define HISTORY_SIZE 30\n")
    f.write("static char cmd_history[HISTORY_SIZE][CMD_BUF_SIZE];\n")
    f.write("static int hist_count = 0;\n")
    f.write("static int hist_next = 0;\n\n")
    f.write("#define ENV_MAX 32\n")
    f.write("static char env_vars[ENV_MAX][2][64];\n")
    f.write("static int env_count = 0;\n\n")
    f.write("#define ALIAS_MAX 16\n")
    f.write("static char alias_names[ALIAS_MAX][32];\n")
    f.write("static char alias_cmds[ALIAS_MAX][128];\n")
    f.write("static int alias_count = 0;\n\n")
    f.write("static void add_history(const char* cmd) {\n")
    f.write("    if (strlen(cmd) == 0) return;\n")
    f.write("    strncpy(cmd_history[hist_next], cmd, CMD_BUF_SIZE - 1);\n")
    f.write("    cmd_history[hist_next][CMD_BUF_SIZE - 1] = '\\0';\n")
    f.write("    hist_next = (hist_next + 1) % HISTORY_SIZE;\n")
    f.write("    if (hist_count < HISTORY_SIZE) hist_count++;\n")
    f.write("}\n\n")
    f.write("static const char* resolve_alias(const char* cmd) {\n")
    f.write("    for (int i = 0; i < alias_count; i++) {\n")
    f.write("        if (strcmp(cmd, alias_names[i]) == 0) return alias_cmds[i];\n")
    f.write("    }\n")
    f.write("    return cmd;\n")
    f.write("}\n\n")
    f.write("static int startswith(const char* s, const char* prefix) {\n")
    f.write("    return strncmp(s, prefix, strlen(prefix)) == 0;\n")
    f.write("}\n\n")
    f.write("static void print_prompt(void) {\n")
    f.write("    vga_set_color(VGA_LIGHT_GREEN, VGA_BLACK);\n")
    f.write("    vga_puts(user_get_name());\n")
    f.write("    vga_set_color(VGA_WHITE, VGA_BLACK);\n")
    f.write("    vga_puts(\"@byo-os\");\n")
    f.write("    vga_set_color(VGA_LIGHT_GREY, VGA_BLACK);\n")
    f.write("    vga_puts(\"> \");\n")
    f.write("}\n\n")
print("Part 1 written")
