const fs = require('fs');
const shell = 'E:/aisystem/byo-os/kernel/shell.c';
let c = fs.readFileSync(shell, 'utf8');
let lines = c.split('\n');
const tableIdx = lines.findIndex(l => l.includes('static const cmd_entry commands[]'));
let endIdx = -1;
for (let i = tableIdx; i < lines.length; i++) { if (lines[i].includes('{0, 0}')) { endIdx = i; break; } }

const b12 = [];
const f = (s) => b12.push(s);

// B12: Database tools
f('/* BATCH 12: Database */');
f('static void cmd_mysql(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: mysql [-u user] [db]\\n"); return; }');
f('    vga_puts("mysql 8.0.35\\nType \\"help\\" for help.\\nmysql> \\n");');
f('}');
f('');
f('static void cmd_psql(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("psql (PostgreSQL) 15.0\\nType \\"help\\" for help.\\n=> \\n");');
f('}');
f('');
f('static void cmd_sqlite3(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("SQLite 3.40.0\\nsqlite> \\n");');
f('}');
f('');
f('static void cmd_mongosh(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("mongosh 2.0.0\\n> \\n");');
f('}');
f('');
f('static void cmd_redis_cli(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("redis-cli 7.0.0\\n127.0.0.1:6379> \\n");');
f('}');
f('');
f('static void cmd_pg_isready(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("postgresql: accepting connections\\n");');
f('}');
f('');
f('static void cmd_mysqldump(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: mysqldump [db]\\n"); return; }');
f('    vga_puts("-- Dump completed --\\n");');
f('}');
f('');
// B12: Email
f('/* BATCH 12: Email */');
f('static void cmd_mail(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("mail: 2 messages, 2 new\\n");');
f('    vga_puts("N  1 root  Jan 15 12:00  Welcome to BYO-OS\\n");');
f('    vga_puts("N  2 root  Jan 15 12:01  System ready\\n");');
f('}');
f('');
f('static void cmd_sendmail(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("sendmail: message queued\\n");');
f('}');
f('');
f('static void cmd_msmtp(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("msmtp: SMTP client\\n");');
f('}');
f('');
f('static void cmd_fetchmail(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("fetchmail: no messages\\n");');
f('}');
f('');
f('static void cmd_procmail(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("procmail: mail delivery agent\\n");');
f('}');
f('');
// B12: Web services
f('/* BATCH 12: Web Services */');
f('static void cmd_nginx(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: nginx [start|stop|reload|status]\\n"); return; }');
f('    if (strcmp(args[1], "start") == 0) vga_puts("nginx: started\\n");');
f('    else if (strcmp(args[1], "stop") == 0) vga_puts("nginx: stopped\\n");');
f('    else if (strcmp(args[1], "reload") == 0) vga_puts("nginx: reloaded\\n");');
f('    else if (strcmp(args[1], "status") == 0) vga_puts("nginx: running\\n");');
f('}');
f('');
f('static void cmd_apache2(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: apache2 [start|stop|restart|status]\\n"); return; }');
f('    vga_puts("apache2: operation completed\\n");');
f('}');
f('');
f('static void cmd_apachectl(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: apachectl [start|stop|restart]\\n"); return; }');
f('    vga_puts("apachectl: operation completed\\n");');
f('}');
f('');
f('static void cmd_phpfpm(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("php-fpm: FastCGI process manager\\n");');
f('}');
f('');
f('static void cmd_uwsgi(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("uWSGI: application server\\n");');
f('}');
f('');
f('static void cmd_gunicorn(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("gunicorn: WSGI HTTP server\\n");');
f('}');
f('');
// B12: DNS server
f('/* BATCH 12: DNS Server */');
f('static void cmd_bind9(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("bind9: DNS server\\nUsage: named -g\\n");');
f('}');
f('');
f('static void cmd_dnsmasq(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("dnsmasq: DNS/DHCP server\\n");');
f('}');
f('');
f('static void cmd_unbound(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("unbound: DNS resolver\\n");');
f('}');
f('');
// B12: DHCP
f('/* BATCH 12: DHCP */');
f('static void cmd_dhclient(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("dhclient: DHCP client\\n");');
f('}');
f('');
f('static void cmd_dhcpd(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("dhcpd: DHCP server\\n");');
f('}');
f('');
// B12: NTP
f('/* BATCH 12: NTP */');
f('static void cmd_ntpd(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ntpd: NTP daemon\\n");');
f('}');
f('');
f('static void cmd_ntpdate(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ntpdate: time synchronized\\n");');
f('}');
f('');
f('static void cmd_chronyd(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("chronyd: NTP server\\n");');
f('}');
f('');
// B12: Print
f('/* BATCH 12: Print */');
f('static void cmd_lpr(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: lpr <file>\\n"); return; }');
f('    vga_puts("lpr: job queued\\n");');
f('}');
f('');
f('static void cmd_lpstat(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("printer: idle\\nQueue: empty\\n");');
f('}');
f('');
f('static void cmd_lpq(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Queue: empty\\n");');
f('}');
f('');
f('static void cmd_lprm(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("lprm: job removed\\n");');
f('}');
f('');
f('static void cmd_cups(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: cups [start|stop|status]\\n"); return; }');
f('    vga_puts("cups: operation completed\\n");');
f('}');
f('');
// B12: Cron
f('/* BATCH 12: Scheduler Advanced */');
f('static void cmd_cron(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: cron [start|stop|status]\\n"); return; }');
f('    vga_puts("cron: operation completed\\n");');
f('}');
f('');
f('static void cmd_at(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: at <time>\\n"); return; }');
f('    vga_puts("job queued\\n");');
f('}');
f('');
f('static void cmd_batch(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("batch: when system load < 0.8\\n");');
f('}');
f('');
// B12: Log management
f('/* BATCH 12: Logging */');
f('static void cmd_logrotate(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("logrotate: rotating logs\\n");');
f('}');
f('');
f('static void cmd_rsyslog(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: rsyslog [start|stop|status]\\n"); return; }');
f('    vga_puts("rsyslog: operation completed\\n");');
f('}');
f('');
f('static void cmd_syslog_ng(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("syslog-ng: enhanced logging\\n");');
f('}');
f('');
f('static void cmd_swaks(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("swaks: SMTP test tool\\n");');
f('}');
f('');
// B12: SSH server
f('/* BATCH 12: SSH Server */');
f('static void cmd_sshd(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: sshd [start|stop|status]\\n"); return; }');
f('    vga_puts("sshd: operation completed\\n");');
f('}');
f('');
f('static void cmd_ssh_keygen(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Generating public/private rsa key pair.\\n");');
f('    vga_puts("Your identification has been saved in /root/.ssh/id_rsa\\n");');
f('}');
f('');
f('static void cmd_ssh_agent(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ssh-agent: started\\n");');
f('}');
f('');
// B12: System monitoring
f('/* BATCH 12: System Monitoring */');
f('static void cmd_prometheus(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("prometheus: monitoring system\\n");');
f('}');
f('');
f('static void cmd_grafana(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("grafana: analytics platform\\n");');
f('}');
f('');
f('static void cmd_collectd(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("collectd: statistics collection daemon\\n");');
f('}');
f('');
f('static void cmd_monit(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("monit: process supervisor\\n");');
f('}');
f('');
// B12: Backup advanced
f('/* BATCH 12: Backup Advanced */');
f('static void cmd_borg(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: borg [create|list|extract]\\n"); return; }');
f('    vga_puts("borg: deduplicating backup\\n");');
f('}');
f('');
f('static void cmd_restic(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("restic: backup tool\\n");');
f('}');
f('');
f('static void cmd_duplicity(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("duplicity: incremental backup\\n");');
f('}');
f('');
f('static void cmd_rsnapshot(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("rsnapshot: rsync-based backup\\n");');
f('}');
f('');
// B12: Misc system
f('/* BATCH 12: Misc System */');
f('static void cmd_powertop(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("PowerTOP: Power management\\n\\nTotal: 0 wakeups\\n");');
f('}');
f('');
f('static void cmd_tlp(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("TLP: Advanced Power Management\\n");');
f('}');
f('');
f('static void cmd_cpupower(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("cpu0:频率 2400MHz  策略: powersave\\n");');
f('}');
f('');
f('static void cmd_lscpu(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Architecture:\\tx86\\nCPU(s):\\t1\\nModel name:\\tBYO Virtual CPU\\n");');
f('}');
f('');
f('static void cmd_lshw(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("*-memory\\n  size: 64MiB\\n*-disk\\n  size: 128MiB\\n*-network\\n  description: NE2000\\n");');
f('}');
f('');
f('static void cmd_lsusb(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Bus 001 Device 001: ID 8087:0026\\n");');
f('}');
f('');
f('static void cmd_lspci(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("00:01.0 VGA: BYO VGA\\n00:02.0 Ethernet: NE2000\\n");');
f('}');
f('');
f('static void cmd_lsmod(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Module     Size  Used by\\nne2000    8192  1\\n");');
f('}');
f('');
f('static void cmd_modprobe(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: modprobe <module>\\n"); return; }');
f('    vga_puts("modprobe: "); vga_puts(args[1]); vga_puts(" loaded\\n");');
f('}');
f('');
f('static void cmd_insmod(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: insmod <module>\\n"); return; }');
f('    vga_puts("insmod: "); vga_puts(args[1]); vga_puts(" inserted\\n");');
f('}');
f('');
f('static void cmd_rmmod(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: rmmod <module>\\n"); return; }');
f('    vga_puts("rmmod: "); vga_puts(args[1]); vga_puts(" removed\\n");');
f('}');
f('');
f('static void cmd_dmesg_clear(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("dmesg: buffer cleared\\n");');
f('}');
f('');
f('static void cmd_halt_imp(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("System halted.\\n");');
f('}');
f('');
f('static void cmd_poweroff(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Powering off...\\n");');
f('}');
f('');
f('static void cmd_init_cmd(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: init [0-6]\\n"); return; }');
f('    vga_puts("init: changing to runlevel "); vga_puts(args[1]); vga_puts("\\n");');
f('}');
f('');
f('static void cmd_runlevel(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("N 5\\n");');
f('}');
f('');
f('static void cmd_service_imp(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: service <name> [start|stop|status]\\n"); return; }');
f('    vga_puts(args[1]); vga_puts(": operation completed\\n");');
f('}');
f('');
f('static void cmd_update_rtc(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("RTC updated\\n");');
f('}');
f('');
f('static void cmd_hwclock(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("2025-01-15 12:00:00.000000+00:00\\n");');
f('}');
f('');
f('static void cmd_losetup(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("/dev/loop0: [0] (byo-os)\\n");');
f('}');
f('');
f('static void cmd_dmsetup(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("dmsetup: device-mapper\\n");');
f('}');
f('');
f('static void cmd_parted(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("GNU Parted 3.6\\nModel: BYO Disk\\nSize: 128MB\\n");');
f('}');
f('');
f('static void cmd_gdisk(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("GPT fdisk: partition editor\\n");');
f('}');
f('');
f('static void cmd_fdisk_imp(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Disk /dev/sda: 128MB\\n/dev/sda1 * 62.5M\\n");');
f('}');
f('');
f('static void block_device_info(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Block devices:\\n  sda  128M\\n  sda1 62.5M /\\n");');
f('}');

// Insert functions before table
lines.splice(tableIdx, 0, ...b12);

// Find new end
let newEnd = -1;
for (let i = tableIdx + b12.length; i < lines.length; i++) { if (lines[i].includes('{0, 0}')) { newEnd = i; break; } }

// Table entries
const e12 = [];
e12.push('    /* Batch 12: Database */');
e12.push('    {"mysql", cmd_mysql}, {"psql", cmd_psql}, {"sqlite3", cmd_sqlite3},');
e12.push('    {"mongosh", cmd_mongosh}, {"redis-cli", cmd_redis_cli},');
e12.push('    {"pg_isready", cmd_pg_isready}, {"mysqldump", cmd_mysqldump},');
e12.push('    /* Batch 12: Email */');
e12.push('    {"mail", cmd_mail}, {"sendmail", cmd_sendmail}, {"msmtp", cmd_msmtp},');
e12.push('    {"fetchmail", cmd_fetchmail}, {"procmail", cmd_procmail},');
e12.push('    /* Batch 12: Web Services */');
e12.push('    {"nginx", cmd_nginx}, {"apache2", cmd_apache2}, {"apachectl", cmd_apachectl},');
e12.push('    {"php-fpm", cmd_phpfpm}, {"uwsgi", cmd_uwsgi}, {"gunicorn", cmd_gunicorn},');
e12.push('    /* Batch 12: DNS/DHCP/NTP */');
e12.push('    {"named", cmd_bind9}, {"dnsmasq", cmd_dnsmasq}, {"unbound", cmd_unbound},');
e12.push('    {"dhclient", cmd_dhclient}, {"dhcpd", cmd_dhcpd},');
e12.push('    {"ntpd", cmd_ntpd}, {"ntpdate", cmd_ntpdate}, {"chronyd", cmd_chronyd},');
e12.push('    /* Batch 12: Print */');
e12.push('    {"lpr", cmd_lpr}, {"lpstat", cmd_lpstat}, {"lpq", cmd_lpq}, {"lprm", cmd_lprm}, {"cups", cmd_cups},');
e12.push('    /* Batch 12: Scheduler */');
e12.push('    {"at", cmd_at}, {"batch", cmd_batch},');
e12.push('    /* Batch 12: Logging */');
e12.push('    {"logrotate", cmd_logrotate}, {"rsyslog", cmd_rsyslog}, {"syslog-ng", cmd_syslog_ng}, {"swaks", cmd_swaks},');
e12.push('    /* Batch 12: SSH Server */');
e12.push('    {"sshd", cmd_sshd}, {"ssh-keygen", cmd_ssh_keygen}, {"ssh-agent", cmd_ssh_agent},');
e12.push('    /* Batch 12: Monitoring */');
e12.push('    {"prometheus", cmd_prometheus}, {"grafana", cmd_grafana}, {"collectd", cmd_collectd}, {"monit", cmd_monit},');
e12.push('    /* Batch 12: Backup Advanced */');
e12.push('    {"borg", cmd_borg}, {"restic", cmd_restic}, {"duplicity", cmd_duplicity}, {"rsnapshot", cmd_rsnapshot},');
e12.push('    /* Batch 12: Power */');
e12.push('    {"powertop", cmd_powertop}, {"tlp", cmd_tlp}, {"cpupower", cmd_cpupower},');
e12.push('    /* Batch 12: Hardware */');
e12.push('    {"lscpu", cmd_lscpu}, {"lshw", cmd_lshw}, {"lsusb", cmd_lsusb}, {"lspci", cmd_lspci},');
e12.push('    {"lsmod", cmd_lsmod}, {"modprobe", cmd_modprobe}, {"insmod", cmd_insmod}, {"rmmod", cmd_rmmod},');
e12.push('    /* Batch 12: System Control */');
e12.push('    {"poweroff", cmd_poweroff}, {"init", cmd_init_cmd}, {"runlevel", cmd_runlevel},');
e12.push('    {"hwclock", cmd_hwclock}, {"losetup", cmd_losetup}, {"dmsetup", cmd_dmsetup},');
e12.push('    {"parted", cmd_parted}, {"gdisk", cmd_gdisk}, {"lsblk_adv", block_device_info},');

lines.splice(newEnd, 0, ...e12);
fs.writeFileSync(shell, lines.join('\n'), 'utf8');
console.log('Batch 12 applied! Lines:', lines.length);
