const fs = require('fs');
const shell = 'E:/aisystem/byo-os/kernel/shell.c';
let c = fs.readFileSync(shell, 'utf8');
let lines = c.split('\n');
const tableIdx = lines.findIndex(l => l.includes('static const cmd_entry commands[]'));
let endIdx = -1;
for (let i = tableIdx; i < lines.length; i++) { if (lines[i].includes('{0, 0}')) { endIdx = i; break; } }

const b17 = [];
const f = (s) => b17.push(s);

f('/* BATCH 17: Service Mesh */');
f('static void cmd_istioctl(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("istioctl: Istio CLI\\n");');
f('}');
f('');
f('static void cmd_kuma(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Kuma: service mesh\\n");');
f('}');
f('');
f('/* BATCH 17: API Gateway */');
f('static void cmd_kong(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Kong: API gateway\\n");');
f('}');
f('');
f('static void cmd_apisix(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Apache APISIX: API gateway\\n");');
f('}');
f('');
f('static void cmd_tyk(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Tyk: API gateway\\n");');
f('}');
f('');
f('/* BATCH 17: Serverless */');
f('static void cmd_openfaas(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("OpenFaaS: serverless functions\\n");');
f('}');
f('');
f('static void cmd_knative(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Knative: serverless platform\\n");');
f('}');
f('');
f('static void cmd_fission(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Fission: serverless functions\\n");');
f('}');
f('');
f('/* BATCH 17: PostgreSQL HA */');
f('static void cmd_citus(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Citus: distributed PostgreSQL\\n");');
f('}');
f('');
f('static void cmd_vitess(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Vitess: database clustering\\n");');
f('}');
f('');
f('static void cmd_patroni(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Patroni: PostgreSQL HA\\n");');
f('}');
f('');
f('static void cmd_pgbouncer(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("PgBouncer: connection pooler\\n");');
f('}');
f('');
f('static void cmd_repmgr(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("repmgr: replication manager\\n");');
f('}');
f('');
f('static void cmd_barman(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Barman: backup manager\\n");');
f('}');
f('');
f('static void cmd_pgbackrest(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("pgBackRest: PostgreSQL backup\\n");');
f('}');
f('');
f('/* BATCH 17: Data Pipeline */');
f('static void cmd_airflow(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Apache Airflow: workflow orchestration\\n");');
f('}');
f('');
f('static void cmd_dagster(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Dagster: data orchestrator\\n");');
f('}');
f('');
f('static void cmd_dbt(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("dbt: data transformation\\n");');
f('}');
f('');
f('static void cmd_spark(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Apache Spark: analytics engine\\n");');
f('}');
f('');
f('static void cmd_flink(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Apache Flink: stream processing\\n");');
f('}');
f('');
f('/* BATCH 17: Service Discovery */');
f('static void cmd_etcd(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("etcd: distributed KV store\\n");');
f('}');
f('');
f('static void cmd_zookeeper(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ZooKeeper: coordination service\\n");');
f('}');
f('');
f('static void cmd_nacos(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Nacos: service discovery\\n");');
f('}');
f('');
f('/* BATCH 17: Cache */');
f('static void cmd_hazelcast(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Hazelcast: in-memory computing\\n");');
f('}');
f('');
f('static void cmd_keydb(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("KeyDB: Redis fork\\n");');
f('}');
f('');
f('static void cmd_dragonfly(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Dragonfly: Redis replacement\\n");');
f('}');
f('');
f('/* BATCH 17: Monitoring Extended */');
f('static void cmd_thanos(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Thanos: Prometheus HA\\n");');
f('}');
f('');
f('static void cmd_victoriametrics(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("VictoriaMetrics: metrics\\n");');
f('}');
f('');
f('static void cmd_netdata(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Netdata: real-time monitoring\\n");');
f('}');
f('');
f('static void cmd_uptimekuma(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Uptime Kuma: uptime monitor\\n");');
f('}');
f('');
f('/* BATCH 17: Security */');
f('static void cmd_trivy(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Trivy: vulnerability scanner\\n");');
f('}');
f('');
f('static void cmd_grype(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Grype: vulnerability scanner\\n");');
f('}');
f('');
f('static void cmd_syft(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Syft: SBOM generator\\n");');
f('}');
f('');
f('static void cmd_cosign(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Cosign: container signing\\n");');
f('}');
f('');
f('static void cmd_sonarqube(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("SonarQube: code quality\\n");');
f('}');
f('');
f('static void cmd_watchtower(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Watchtower: container updater\\n");');
f('}');
f('');
f('/* BATCH 17: Browser */');
f('static void cmd_brave_browser(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Brave: privacy browser\\n");');
f('}');
f('');
f('static void cmd_tor(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Tor Browser\\n");');
f('}');
f('');
f('/* BATCH 17: P2P */');
f('static void cmd_ipfs(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("IPFS: distributed web\\n");');
f('}');
f('');
f('static void cmd_i2p(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("I2P: anonymous network\\n");');
f('}');
f('');
f('/* BATCH 17: Matrix */');
f('static void cmd_synapse(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Synapse: Matrix homeserver\\n");');
f('}');
f('');
f('static void cmd_dendrite(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Dendrite: Matrix homeserver\\n");');
f('}');
f('');
f('static void cmd_mautrix_tg(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("mautrix-telegram: Telegram bridge\\n");');
f('}');
f('');
f('static void cmd_mautrix_wa(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("mautrix-whatsapp: WhatsApp bridge\\n");');
f('}');
f('');
f('static void cmd_mautrix_dc(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("mautrix-discord: Discord bridge\\n");');
f('}');
f('');
f('static void cmd_mautrix_sig(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("mautrix-signal: Signal bridge\\n");');
f('}');
f('');
f('/* BATCH 17: Messaging Extended */');
f('static void cmd_nsq(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("NSQ: real-time messaging\\n");');
f('}');
f('');
f('static void cmd_pulsar(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Pulsar: event streaming\\n");');
f('}');
f('');
f('static void cmd_mqtt_sub(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("mosquitto_sub: MQTT subscriber\\n");');
f('}');
f('');
f('static void cmd_mqtt_pub(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("mosquitto_pub: MQTT publisher\\n");');
f('}');
f('');
f('/* BATCH 17: Misc */');
f('static void cmd_kafka_connect(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Kafka Connect: data integration\\n");');
f('}');
f('');
f('static void cmd_kcat(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("kcat: Kafka CLI\\n");');
f('}');
f('');
f('static void cmd_renovate(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Renovate: dependency updater\\n");');
f('}');
f('');
f('static void cmd_grafana_agent(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Grafana Agent: telemetry collector\\n");');
f('}');
f('');
f('static void cmd_vector(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Vector: data pipeline\\n");');
f('}');
f('');
f('static void cmd_fluentd(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Fluentd: data collector\\n");');
f('}');
f('');
f('static void cmd_fluentbit(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Fluent Bit: log processor\\n");');
f('}');
f('');
f('static void cmd_filebeat(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Filebeat: log shipper\\n");');
f('}');
f('');
f('static void cmd_logstash(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Logstash: log processing\\n");');
f('}');
f('');
f('static void cmd_kibana(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Kibana: visualization\\n");');
f('}');
f('');
f('static void cmd_telegraf(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Telegraf: metrics collection\\n");');
f('}');
f('');
f('static void cmd_containerruntime(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("containerd: OCI runtime\\n");');
f('}');
f('');
f('static void cmd_crio(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("CRI-O: Kubernetes runtime\\n");');
f('}');
f('');
f('static void cmd_runc(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("runc: OCI runtime\\n");');
f('}');
f('');
f('static void cmd_crictl(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("crictl: CRI CLI\\n");');
f('}');
f('');
f('static void cmd_buildah(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Buildah: container image builder\\n");');
f('}');
f('');
f('static void cmd_skopeo(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Skopeo: image operations\\n");');
f('}');

// Insert functions before table
lines.splice(tableIdx, 0, ...b17);

// Find new end
let newEnd = -1;
for (let i = tableIdx + b17.length; i < lines.length; i++) { if (lines[i].includes('{0, 0}')) { newEnd = i; break; } }

// Table entries
const e17 = [];
e17.push('    /* Batch 17: Service Mesh */');
e17.push('    {"istioctl", cmd_istioctl}, {"kuma", cmd_kuma},');
e17.push('    /* Batch 17: API Gateway */');
e17.push('    {"kong", cmd_kong}, {"apisix", cmd_apisix}, {"tyk", cmd_tyk},');
e17.push('    /* Batch 17: Serverless */');
e17.push('    {"openfaas", cmd_openfaas}, {"knative", cmd_knative}, {"fission", cmd_fission},');
e17.push('    /* Batch 17: PostgreSQL HA */');
e17.push('    {"citus", cmd_citus}, {"vitess", cmd_vitess}, {"patroni", cmd_patroni},');
e17.push('    {"pgbouncer", cmd_pgbouncer}, {"repmgr", cmd_repmgr},');
e17.push('    {"barman", cmd_barman}, {"pgbackrest", cmd_pgbackrest},');
e17.push('    /* Batch 17: Data Pipeline */');
e17.push('    {"airflow", cmd_airflow}, {"dagster", cmd_dagster}, {"dbt", cmd_dbt},');
e17.push('    {"spark", cmd_spark}, {"flink", cmd_flink},');
e17.push('    /* Batch 17: Service Discovery */');
e17.push('    {"etcd", cmd_etcd}, {"zookeeper", cmd_zookeeper}, {"nacos", cmd_nacos},');
e17.push('    /* Batch 17: Cache */');
e17.push('    {"hazelcast", cmd_hazelcast}, {"keydb", cmd_keydb}, {"dragonfly", cmd_dragonfly},');
e17.push('    /* Batch 17: Monitoring Extended */');
e17.push('    {"thanos", cmd_thanos}, {"victoriametrics", cmd_victoriametrics},');
e17.push('    {"netdata", cmd_netdata}, {"uptime-kuma", cmd_uptimekuma},');
e17.push('    /* Batch 17: Security */');
e17.push('    {"trivy", cmd_trivy}, {"grype", cmd_grype}, {"syft", cmd_syft}, {"cosign", cmd_cosign},');
e17.push('    {"sonarqube", cmd_sonarqube}, {"watchtower", cmd_watchtower}, {"renovate", cmd_renovate},');
e17.push('    /* Batch 17: Browser */');
e17.push('    {"brave-browser", cmd_brave_browser}, {"tor", cmd_tor},');
e17.push('    /* Batch 17: P2P */');
e17.push('    {"ipfs", cmd_ipfs}, {"i2p", cmd_i2p},');
e17.push('    /* Batch 17: Matrix */');
e17.push('    {"synapse", cmd_synapse}, {"dendrite", cmd_dendrite},');
e17.push('    {"mautrix-telegram", cmd_mautrix_tg}, {"mautrix-whatsapp", cmd_mautrix_wa},');
e17.push('    {"mautrix-discord", cmd_mautrix_dc}, {"mautrix-signal", cmd_mautrix_sig},');
e17.push('    /* Batch 17: Messaging Extended */');
e17.push('    {"nsq", cmd_nsq}, {"pulsar", cmd_pulsar},');
e17.push('    {"mosquitto-sub", cmd_mqtt_sub}, {"mosquitto-pub", cmd_mqtt_pub},');
e17.push('    {"kafka-connect", cmd_kafka_connect}, {"kcat", cmd_kcat},');
e17.push('    /* Batch 17: Observability */');
e17.push('    {"grafana-agent", cmd_grafana_agent}, {"vector", cmd_vector},');
e17.push('    {"fluentd", cmd_fluentd}, {"fluent-bit", cmd_fluentbit},');
e17.push('    {"filebeat", cmd_filebeat}, {"logstash", cmd_logstash}, {"kibana", cmd_kibana},');
e17.push('    {"telegraf", cmd_telegraf},');
e17.push('    /* Batch 17: Container Runtime */');
e17.push('    {"containerd", cmd_containerruntime}, {"cri-o", cmd_crio}, {"runc", cmd_runc},');
e17.push('    {"crictl", cmd_crictl}, {"buildah", cmd_buildah}, {"skopeo", cmd_skopeo},');

lines.splice(newEnd, 0, ...e17);
fs.writeFileSync(shell, lines.join('\n'), 'utf8');
console.log('Batch 17 applied! Lines:', lines.length);
