const fs = require('fs');
const shell = 'E:/aisystem/byo-os/kernel/shell.c';
let c = fs.readFileSync(shell, 'utf8');
let lines = c.split('\n');
const tableIdx = lines.findIndex(l => l.includes('static const cmd_entry commands[]'));
let endIdx = -1;
for (let i = tableIdx; i < lines.length; i++) { if (lines[i].includes('{0, 0}')) { endIdx = i; break; } }

const b15 = [];
const f = (s) => b15.push(s);

// B15: Networking Services
f('/* BATCH 15: Network Services */');
f('static void cmd_samba(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Samba: SMB/CIFS file server\\n");');
f('}');
f('');
f('static void cmd_nfs(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("NFS: Network File System\\n");');
f('}');
f('');
f('static void cmd_ftp_server(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("vsftpd: FTP server\\n");');
f('}');
f('');
f('static void cmd_scp_server(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("OpenSSH SCP server\\n");');
f('}');
f('');
f('static void cmd_rsync_server(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("rsync daemon\\n");');
f('}');
f('');
f('static void cmd_tftp(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("TFTP: Trivial FTP\\n");');
f('}');
f('');
f('static void cmd_xinetd(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("xinetd: extended internet services\\n");');
f('}');
f('');
f('static void cmd_stunnel(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("stunnel: SSL tunnel\\n");');
f('}');
f('');
f('static void cmd_haproxy_server(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("HAProxy: load balancer\\n");');
f('}');
f('');
f('static void cmd_keepalived(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Keepalived: VRRP\\n");');
f('}');
f('');
// B15: Mail Server
f('/* BATCH 15: Mail Server */');
f('static void cmd_postfix(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Postfix: MTA\\n");');
f('}');
f('');
f('static void cmd_dovecot(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Dovecot: IMAP/POP3 server\\n");');
f('}');
f('');
f('static void cmd_spamassassin(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("SpamAssassin: spam filter\\n");');
f('}');
f('');
f('static void cmd_clamav_milter(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ClamAV milter: mail antivirus\\n");');
f('}');
f('');
// B15: Virtualization
f('/* BATCH 15: Virtualization */');
f('static void cmd_qemu_system(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("QEMU: system emulator\\n");');
f('}');
f('');
f('static void cmd_vboxmanage(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("VirtualBox: VM manager\\n");');
f('}');
f('');
f('static void cmd_virsh(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: virsh [list|start|stop|info]\\n"); return; }');
f('    if (strcmp(args[1], "list") == 0) {');
f('        vga_puts("Id Name                 State\\n------------------------------------\\n");');
f('    } else { vga_puts("virsh: operation completed\\n"); }');
f('}');
f('');
f('static void cmd_xen(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Xen: hypervisor\\n");');
f('}');
f('');
f('static void cmd_kvm(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("KVM: kernel-based VM\\n");');
f('}');
f('');
f('static void cmd_lxc(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("LXC: Linux containers\\n");');
f('}');
f('');
f('static void cmd_proxmox(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Proxmox VE: virtual environment\\n");');
f('}');
f('');
// B15: Storage
f('/* BATCH 15: Storage */');
f('static void cmd_ceph(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Ceph: distributed storage\\n");');
f('}');
f('');
f('static void cmd_minio(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("MinIO: S3-compatible storage\\n");');
f('}');
f('');
f('static void cmd_glusterfs(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("GlusterFS: distributed filesystem\\n");');
f('}');
f('');
f('static void cmd_nfs_server(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("NFS server: /exports\\n");');
f('}');
f('');
f('static void cmd_iscsi(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("iSCSI: block storage\\n");');
f('}');
f('');
f('static void cmd_fc(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Fibre Channel: SAN\\n");');
f('}');
f('');
// B15: Authentication
f('/* BATCH 15: Authentication */');
f('static void cmd_ldap(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("OpenLDAP: directory service\\n");');
f('}');
f('');
f('static void cmd_kerberos(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Kerberos: authentication\\n");');
f('}');
f('');
f('static void cmd_sssd(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("SSSD: system security services\\n");');
f('}');
f('');
f('static void cmd_pam(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("PAM: pluggable authentication\\n");');
f('}');
f('');
f('static void cmd_sudo_ldap(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("sudo-ldap: LDAP-based sudo\\n");');
f('}');
f('');
// B15: Monitoring Extended
f('/* BATCH 15: Monitoring Extended */');
f('static void cmd_cacti(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Cacti: network monitoring\\n");');
f('}');
f('');
f('static void cmd_munin(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Munin: resource monitoring\\n");');
f('}');
f('');
f('static void cmd_icinga(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Icinga: monitoring system\\n");');
f('}');
f('');
f('static void cmd_datadog(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Datadog: cloud monitoring\\n");');
f('}');
f('');
f('static void cmd_newrelic(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("New Relic: observability\\n");');
f('}');
f('');
f('static void cmd_sentry(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Sentry: error tracking\\n");');
f('}');
f('');
// B15: CI/CD Extended
f('/* BATCH 15: CI/CD Extended */');
f('static void cmd_drone(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Drone: CI/CD platform\\n");');
f('}');
f('');
f('static void cmd_argo(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ArgoCD: GitOps\\n");');
f('}');
f('');
f('static void cmd_flux(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Flux: GitOps toolkit\\n");');
f('}');
f('');
f('static void cmd_tekton(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Tekton: cloud-native CI/CD\\n");');
f('}');
f('');
f('static void cmd_concourse(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Concourse: CI/CD\\n");');
f('}');
f('');
// B15: Security Extended
f('/* BATCH 15: Security Extended */');
f('static void cmd_crowdsec(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("CrowdSec: collaborative security\\n");');
f('}');
f('');
f('static void cmd_authelia(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Authelia: SSO authentication\\n");');
f('}');
f('');
f('static void cmd_keycloak(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Keycloak: identity management\\n");');
f('}');
f('');
f('static void cmd_dex(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Dex: OpenID Connect provider\\n");');
f('}');
f('');
f('static void cmd_oauth2_proxy(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("OAuth2 Proxy: authentication proxy\\n");');
f('}');
f('');
// B15: Misc Extended
f('/* BATCH 15: Misc Extended */');
f('static void cmd_gitea(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Gitea: self-hosted Git\\n");');
f('}');
f('');
f('static void cmd_gitlab(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("GitLab: DevOps platform\\n");');
f('}');
f('');
f('static void cmd_gogs(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Gogs: self-hosted Git\\n");');
f('}');
f('');
f('static void cmd_nextcloud(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Nextcloud: file sync\\n");');
f('}');
f('');
f('static void cmd_owncloud(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ownCloud: file sync\\n");');
f('}');
f('');
f('static void cmd_seafile(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Seafile: file sync\\n");');
f('}');
f('');
f('static void cmd_matomo(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Matomo: web analytics\\n");');
f('}');
f('');
f('static void cmd_plausible(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Plausible: privacy-friendly analytics\\n");');
f('}');
f('');
f('static void cmd_umami(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Umami: web analytics\\n");');
f('}');
f('');
f('static void cmd_matomo_cli(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Matomo CLI\\n");');
f('}');
f('');
f('static void cmd_grafana_agent(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Grafana Agent: telemetry collector\\n");');
f('}');
f('');
f('static void cmd_vector(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Vector: data pipeline\\n");');
f('}');
f('');
f('static void cmd_fluentd(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Fluentd: data collector\\n");');
f('}');
f('');
f('static void cmd_fluentbit(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Fluent Bit: log processor\\n");');
f('}');
f('');
f('static void cmd_filebeat(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Filebeat: log shipper\\n");');
f('}');
f('');
f('static void cmd_logstash(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Logstash: log processing\\n");');
f('}');
f('');
f('static void cmd_kibana(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Kibana: visualization\\n");');
f('}');
f('');
f('static void cmd_chronograf(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Chronograf: InfluxDB UI\\n");');
f('}');
f('');
f('static void cmd_kapacitor(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Kapacitor: alerting\\n");');
f('}');
f('');
f('static void cmd_telegraf(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Telegraf: metrics collection\\n");');
f('}');
f('');
f('static void cmd_containerruntime(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("containerd: OCI runtime\\n");');
f('}');
f('');
f('static void cmd_cri_o(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("CRI-O: Kubernetes runtime\\n");');
f('}');
f('');
f('static void cmd_runc(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("runc: OCI runtime\\n");');
f('}');
f('');
f('static void cmd_crictl(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("crictl: CRI CLI\\n");');
f('}');
f('');
f('static void cmd_buildah(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Buildah: container image builder\\n");');
f('}');
f('');
f('static void cmd_skopeo(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Skopeo: image operations\\n");');
f('}');
f('');
f('static void cmd_kaniko(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Kaniko: container image builder\\n");');
f('}');
f('');
f('static void cmd_buildkit(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("BuildKit: container builder\\n");');
f('}');
f('');
f('static void cmd_kaniko_cli(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Kaniko CLI\\n");');
f('}');

// Insert functions before table
lines.splice(tableIdx, 0, ...b15);

// Find new end
let newEnd = -1;
for (let i = tableIdx + b15.length; i < lines.length; i++) { if (lines[i].includes('{0, 0}')) { newEnd = i; break; } }

// Table entries
const e15 = [];
e15.push('    /* Batch 15: Network Services */');
e15.push('    {"samba", cmd_samba}, {"nfs", cmd_nfs}, {"vsftpd", cmd_ftp_server},');
e15.push('    {"tftp", cmd_tftp}, {"xinetd", cmd_xinetd}, {"stunnel", cmd_stunnel},');
e15.push('    {"keepalived", cmd_keepalived},');
e15.push('    /* Batch 15: Mail */');
e15.push('    {"postfix", cmd_postfix}, {"dovecot", cmd_dovecot}, {"spamassassin", cmd_spamassassin},');
e15.push('    /* Batch 15: Virtualization */');
e15.push('    {"virsh", cmd_virsh}, {"vboxmanage", cmd_vboxmanage}, {"xen", cmd_xen}, {"kvm", cmd_kvm},');
e15.push('    {"lxc", cmd_lxc}, {"proxmox", cmd_proxmox},');
e15.push('    /* Batch 15: Storage */');
e15.push('    {"ceph", cmd_ceph}, {"minio", cmd_minio}, {"glusterfs", cmd_glusterfs}, {"iscsi", cmd_iscsi},');
e15.push('    /* Batch 15: Auth */');
e15.push('    {"ldap", cmd_ldap}, {"kerberos", cmd_kerberos}, {"sssd", cmd_sssd}, {"pam", cmd_pam},');
e15.push('    /* Batch 15: Monitoring */');
e15.push('    {"cacti", cmd_cacti}, {"munin", cmd_munin}, {"icinga", cmd_icinga},');
e15.push('    {"datadog", cmd_datadog}, {"newrelic", cmd_newrelic}, {"sentry", cmd_sentry},');
e15.push('    /* Batch 15: CI/CD Extended */');
e15.push('    {"drone", cmd_drone}, {"argocd", cmd_argo}, {"flux", cmd_flux}, {"tekton", cmd_tekton},');
e15.push('    /* Batch 15: Security Extended */');
e15.push('    {"crowdsec", cmd_crowdsec}, {"authelia", cmd_authelia}, {"keycloak", cmd_keycloak}, {"dex", cmd_dex},');
e15.push('    /* Batch 15: Self-hosted */');
e15.push('    {"gitea", cmd_gitea}, {"gitlab", cmd_gitlab}, {"gogs", cmd_gogs},');
e15.push('    {"nextcloud", cmd_nextcloud}, {"owncloud", cmd_owncloud}, {"seafile", cmd_seafile},');
e15.push('    /* Batch 15: Analytics */');
e15.push('    {"matomo", cmd_matomo}, {"plausible", cmd_plausible}, {"umami", cmd_umami},');
e15.push('    /* Batch 15: Observability */');
e15.push('    {"vector", cmd_vector}, {"fluentd", cmd_fluentd}, {"fluent-bit", cmd_fluentbit},');
e15.push('    {"filebeat", cmd_filebeat}, {"logstash", cmd_logstash}, {"kibana", cmd_kibana},');
e15.push('    {"telegraf", cmd_telegraf}, {"kapacitor", cmd_kapacitor},');
e15.push('    /* Batch 15: Container Runtime */');
e15.push('    {"containerd", cmd_containerruntime}, {"cri-o", cmd_cri_o}, {"runc", cmd_runc},');
e15.push('    {"crictl", cmd_crictl}, {"buildah", cmd_buildah}, {"skopeo", cmd_skopeo}, {"buildkit", cmd_buildkit},');

lines.splice(newEnd, 0, ...e15);
fs.writeFileSync(shell, lines.join('\n'), 'utf8');
console.log('Batch 15 applied! Lines:', lines.length);
