const fs = require('fs');
const shell = 'E:/aisystem/byo-os/kernel/shell.c';
let c = fs.readFileSync(shell, 'utf8');
let lines = c.split('\n');
const tableIdx = lines.findIndex(l => l.includes('static const cmd_entry commands[]'));
let endIdx = -1;
for (let i = tableIdx; i < lines.length; i++) { if (lines[i].includes('{0, 0}')) { endIdx = i; break; } }

const b14 = [];
const f = (s) => b14.push(s);

// B14: Advanced Security
f('/* BATCH 14: Advanced Security */');
f('static void cmd_clamav(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ClamAV: antivirus scanner\\n");');
f('}');
f('');
f('static void cmd_aide(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("AIDE: file integrity checker\\n");');
f('}');
f('');
f('static void cmd_tripwire(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Tripwire: intrusion detection\\n");');
f('}');
f('');
f('static void cmd_lynis(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Lynis: security auditing tool\\n");');
f('}');
f('');
f('static void cmd_rkhunter(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("rkhunter: rootkit detector\\n");');
f('}');
f('');
f('static void cmd_chkrootkit(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("chkrootkit: rootkit checker\\n");');
f('}');
f('');
f('static void cmd_ossec(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("OSSEC: host-based IDS\\n");');
f('}');
f('');
f('static void cmd_suricata(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Suricata: IDS/IPS engine\\n");');
f('}');
f('');
f('static void cmd_snort(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Snort: network intrusion detection\\n");');
f('}');
f('');
f('static void cmd_openvas(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("OpenVAS: vulnerability scanner\\n");');
f('}');
f('');
f('static void cmd_nessus(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Nessus: vulnerability scanner\\n");');
f('}');
f('');
f('static void cmd_burpsuite(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Burp Suite: web security testing\\n");');
f('}');
f('');
f('static void cmd_owasp_zap(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("OWASP ZAP: web app security\\n");');
f('}');
f('');
f('static void cmd_hydra(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("THC Hydra: password cracker\\n");');
f('}');
f('');
f('static void cmd_john(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("John the Ripper: password cracker\\n");');
f('}');
f('');
f('static void cmd_hashcat(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("hashcat: password recovery\\n");');
f('}');
f('');
f('static void cmd_ettercap(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ettercap: MITM attack tool\\n");');
f('}');
f('');
f('static void cmd_bettercap(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("bettercap: network attack tool\\n");');
f('}');
f('');
f('static void cmd_reaver(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Reaver: WPS attack tool\\n");');
f('}');
f('');
f('static void cmd_aircrack(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("aircrack-ng: WiFi security\\n");');
f('}');
f('');
f('static void cmd_wifite(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("wifite: automated WiFi attack\\n");');
f('}');
f('');
f('static void cmd_setoolkit(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("SET: Social Engineering Toolkit\\n");');
f('}');
f('');
// B14: Forensics
f('/* BATCH 14: Forensics */');
f('static void cmd_autopsy(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Autopsy: digital forensics\\n");');
f('}');
f('');
f('static void cmd_volatility(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Volatility: memory forensics\\n");');
f('}');
f('');
f('static void cmd_binwalk(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("binwalk: firmware analysis\\n");');
f('}');
f('');
f('static void cmd_foremost(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("foremost: file carving\\n");');
f('}');
f('');
f('static void cmd_strings_adv(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("strings: extract printable strings\\n");');
f('}');
f('');
// B14: Reverse Engineering
f('/* BATCH 14: Reverse Engineering */');
f('static void cmd_ghidra(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Ghidra: software reverse engineering\\n");');
f('}');
f('');
f('static void cmd_radare2(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("radare2: reverse engineering framework\\n");');
f('}');
f('');
f('static void cmd_ida(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("IDA Pro: disassembler\\n");');
f('}');
f('');
f('static void cmd_hexdump_adv(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("hexdump: display hex output\\n");');
f('}');
f('');
// B14: Networking Advanced
f('/* BATCH 14: Network Advanced Tools */');
f('static void cmd_zeek(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Zeek: network security monitor\\n");');
f('}');
f('');
f('static void cmd_wireshark_tshark(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("tshark: terminal Wireshark\\n");');
f('}');
f('');
f('static void cmd_masscan(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("masscan: fast port scanner\\n");');
f('}');
f('');
f('static void cmd_zmap(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("zmap: network scanner\\n");');
f('}');
f('');
f('static void cmd_recon_ng(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("recon-ng: OSINT framework\\n");');
f('}');
f('');
f('static void cmd_theHarvester(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("theHarvester: email/domain harvester\\n");');
f('}');
f('');
f('static void cmd_sublist3r(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Sublist3r: subdomain enumeration\\n");');
f('}');
f('');
f('static void cmd_amass(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Amass: attack surface mapping\\n");');
f('}');
f('');
f('static void cmd_dnsrecon(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("dnsrecon: DNS enumeration\\n");');
f('}');
f('');
f('static void cmd_enum4linux(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("enum4linux: Samba enumeration\\n");');
f('}');
f('');
f('static void cmd_smbclient(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("smbclient: SMB client\\n");');
f('}');
f('');
f('static void cmd_rpcclient(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("rpcclient: RPC client\\n");');
f('}');
f('');
f('static void cmd_windump(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("windump: packet capture\\n");');
f('}');
f('');
// B14: Database Advanced
f('/* BATCH 14: Database Advanced */');
f('static void cmd_mariadb(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("MariaDB 10.11\\n");');
f('}');
f('');
f('static void cmd_cassandra(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Cassandra: distributed database\\n");');
f('}');
f('');
f('static void cmd_elasticsearch(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Elasticsearch 8.0\\n");');
f('}');
f('');
f('static void cmd_couchdb(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("CouchDB: document database\\n");');
f('}');
f('');
f('static void cmd_influxdb(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("InfluxDB: time series database\\n");');
f('}');
f('');
f('static void cmd_neo4j(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Neo4j: graph database\\n");');
f('}');
f('');
f('static void cmd_riak(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Riak: distributed database\\n");');
f('}');
f('');
f('static void cmd_memcached(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Memcached: memory cache\\n");');
f('}');
f('');
f('static void cmd_mongodb(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("MongoDB 6.0\\n");');
f('}');
f('');
// B14: Messaging
f('/* BATCH 14: Messaging */');
f('static void cmd_rabbitmq(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("RabbitMQ: message broker\\n");');
f('}');
f('');
f('static void cmd_kafka(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Kafka: event streaming\\n");');
f('}');
f('');
f('static void cmd_nats(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("NATS: messaging system\\n");');
f('}');
f('');
f('static void cmd_redis_server(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Redis 7.0 server\\n");');
f('}');
f('');
// B14: Web Frameworks
f('/* BATCH 14: Web Frameworks */');
f('static void cmd_rails(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Ruby on Rails 7.0\\n");');
f('}');
f('');
f('static void cmd_django(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Django 4.2\\n");');
f('}');
f('');
f('static void cmd_flask(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Flask 3.0\\n");');
f('}');
f('');
f('static void cmd_laravel(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Laravel 10.0\\n");');
f('}');
f('');
f('static void cmd_spring(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Spring Boot 3.0\\n");');
f('}');
f('');
f('static void cmd_express(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Express.js 4.18\\n");');
f('}');
f('');
f('static void cmd_nextjs(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Next.js 14.0\\n");');
f('}');
f('');
f('static void cmd_react(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("React 18.0\\n");');
f('}');
f('');
f('static void cmd_vue(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Vue.js 3.3\\n");');
f('}');
f('');
f('static void cmd_angular(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Angular 17.0\\n");');
f('}');
f('');
// B14: DevOps
f('/* BATCH 14: DevOps */');
f('static void cmd_grafana_cli(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Grafana CLI 10.0\\n");');
f('}');
f('');
f('static void cmd_loki(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Loki: log aggregation\\n");');
f('}');
f('');
f('static void cmd_tempo(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Tempo: distributed tracing\\n");');
f('}');
f('');
f('static void cmd_mimir(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Mimir: metrics backend\\n");');
f('}');
f('');
f('static void cmd_alertmanager(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Alertmanager: alert routing\\n");');
f('}');
f('');
f('static void cmd_consul(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Consul: service mesh\\n");');
f('}');
f('');
f('static void cmd_vault(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Vault: secrets management\\n");');
f('}');
f('');
f('static void cmd_nomad(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Nomad: workload orchestrator\\n");');
f('}');
f('');
f('static void cmd_waypoint(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Waypoint: deployment platform\\n");');
f('}');
f('');
// B14: AI/ML
f('/* BATCH 14: AI/ML */');
f('static void cmd_tensorflow(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("TensorFlow 2.15\\n");');
f('}');
f('');
f('static void cmd_pytorch(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("PyTorch 2.1\\n");');
f('}');
f('');
f('static void cmd_jupyter(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Jupyter Notebook 7.0\\n");');
f('}');
f('');
f('static void cmd_scipy(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("SciPy 1.11\\n");');
f('}');
f('');
f('static void cmd_numpy(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("NumPy 1.25\\n");');
f('}');
f('');
f('static void cmd_pandas(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("pandas 2.1\\n");');
f('}');
f('');
f('static void cmd_matplotlib(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("matplotlib 3.8\\n");');
f('}');
f('');
f('static void cmd_sklearn(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("scikit-learn 1.3\\n");');
f('}');
f('');
f('static void cmd_openai(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("OpenAI API client\\n");');
f('}');
f('');
f('static void cmd_ollama(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Ollama: local LLM runner\\n");');
f('}');
f('');
// B14: Backup Extended
f('/* BATCH 14: Backup Extended */');
f('static void cmdborg(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("borg: deduplicating backup\\n");');
f('}');
f('');
f('static void cmd_traefik(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Traefik: reverse proxy\\n");');
f('}');
f('');
f('static void cmd_caddy(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Caddy: web server with HTTPS\\n");');
f('}');
f('');
f('static void cmd_envoy(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Envoy: edge/service proxy\\n");');
f('}');
f('');
f('static void cmd_linkerd(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Linkerd: service mesh\\n");');
f('}');
f('');
f('static void cmd_istio(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Istio: service mesh\\n");');
f('}');
f('');
// B14: Misc
f('/* BATCH 14: Misc Advanced */');
f('static void cmd_tldr(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: tldr <command>\\n"); return; }');
f('    vga_puts(args[1]); vga_puts(": simplified man pages\\n");');
f('}');
f('');
f('static void cmd_exa(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("exa: modern ls replacement\\n");');
f('}');
f('');
f('static void cmd_bat(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("bat: cat with syntax highlighting\\n");');
f('}');
f('');
f('static void cmd_fzf(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("fzf: fuzzy finder\\n");');
f('}');
f('');
f('static void cmd_ripgrep(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ripgrep: fast grep\\n");');
f('}');
f('');
f('static void cmd_fd(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("fd: fast find\\n");');
f('}');
f('');
f('static void cmd_dust(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("dust: disk usage\\n");');
f('');
f('static void cmd_duuf(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("duf: disk usage free\\n");');
f('}');
f('');
f('static void cmd_httpie(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("HTTPie: friendly HTTP client\\n");');
f('}');
f('');
f('static void cmd_yq(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("yq: YAML processor\\n");');
f('}');
f('');
f('static void cmd_tokei(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("tokei: code statistics\\n");');
f('}');
f('');
f('static void cmd_cloc(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("cloc: count lines of code\\n");');
f('}');
f('');
f('static void cmd_hey(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("hey: HTTP load generator\\n");');
f('}');
f('');
f('static void cmd_wrk(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("wrk: HTTP benchmarking\\n");');
f('}');
f('');
f('static void cmd_ab(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ab: Apache benchmark\\n");');
f('}');
f('');
f('static void cmd_vegeta(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("vegeta: HTTP load testing\\n");');
f('}');
f('');
f('static void cmd_k6(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("k6: load testing\\n");');
f('}');
f('');
f('static void cmd_locust(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Locust: load testing\\n");');
f('}');
f('');
f('static void cmd_artillery(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Artillery: load testing\\n");');
f('}');
f('');
f('static void cmd_siege(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Siege: HTTP load testing\\n");');
f('}');
f('');
f('static void cmd_jmeter(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("JMeter: performance testing\\n");');
f('}');
f('');
f('static void cmd_gatling(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Gatling: performance testing\\n");');
f('}');

// Insert functions before table
lines.splice(tableIdx, 0, ...b14);

// Find new end
let newEnd = -1;
for (let i = tableIdx + b14.length; i < lines.length; i++) { if (lines[i].includes('{0, 0}')) { newEnd = i; break; } }

// Table entries
const e14 = [];
e14.push('    /* Batch 14: Security Advanced */');
e14.push('    {"clamav", cmd_clamav}, {"aide", cmd_aide}, {"lynis", cmd_lynis},');
e14.push('    {"rkhunter", cmd_rkhunter}, {"chkrootkit", cmd_chkrootkit},');
e14.push('    {"ossec", cmd_ossec}, {"suricata", cmd_suricata}, {"snort", cmd_snort},');
e14.push('    {"openvas", cmd_openvas}, {"nessus", cmd_nessus},');
e14.push('    {"hydra", cmd_hydra}, {"john", cmd_john}, {"hashcat", cmd_hashcat},');
e14.push('    {"ettercap", cmd_ettercap}, {"bettercap", cmd_bettercap},');
e14.push('    {"aircrack", cmd_aircrack}, {"wifite", cmd_wifite}, {"setoolkit", cmd_setoolkit},');
e14.push('    /* Batch 14: Forensics */');
e14.push('    {"autopsy", cmd_autopsy}, {"volatility", cmd_volatility}, {"binwalk", cmd_binwalk}, {"foremost", cmd_foremost},');
e14.push('    /* Batch 14: Reverse Eng */');
e14.push('    {"ghidra", cmd_ghidra}, {"radare2", cmd_radare2}, {"ida", cmd_ida},');
e14.push('    /* Batch 14: Network Tools */');
e14.push('    {"zeek", cmd_zeek}, {"masscan", cmd_masscan}, {"zmap", cmd_zmap},');
e14.push('    {"recon-ng", cmd_recon_ng}, {"amass", cmd_amass}, {"dnsrecon", cmd_dnsrecon},');
e14.push('    {"enum4linux", cmd_enum4linux}, {"smbclient", cmd_smbclient},');
e14.push('    /* Batch 14: Database Extended */');
e14.push('    {"mariadb", cmd_mariadb}, {"cassandra", cmd_cassandra}, {"elasticsearch", cmd_elasticsearch},');
e14.push('    {"couchdb", cmd_couchdb}, {"influxdb", cmd_influxdb}, {"neo4j", cmd_neo4j},');
e14.push('    {"memcached", cmd_memcached}, {"mongodb", cmd_mongodb},');
e14.push('    /* Batch 14: Messaging */');
e14.push('    {"rabbitmq", cmd_rabbitmq}, {"kafka", cmd_kafka}, {"nats", cmd_nats}, {"redis-server", cmd_redis_server},');
e14.push('    /* Batch 14: Web Frameworks */');
e14.push('    {"rails", cmd_rails}, {"django", cmd_django}, {"flask", cmd_flask}, {"laravel", cmd_laravel},');
e14.push('    {"spring", cmd_spring}, {"express", cmd_express}, {"nextjs", cmd_nextjs},');
e14.push('    {"react", cmd_react}, {"vue", cmd_vue}, {"angular", cmd_angular},');
e14.push('    /* Batch 14: DevOps */');
e14.push('    {"loki", cmd_loki}, {"tempo", cmd_tempo}, {"mimir", cmd_mimir}, {"alertmanager", cmd_alertmanager},');
e14.push('    {"consul", cmd_consul}, {"vault", cmd_vault}, {"nomad", cmd_nomad},');
e14.push('    {"traefik", cmd_traefik}, {"caddy", cmd_caddy}, {"envoy", cmd_envoy},');
e14.push('    {"istio", cmd_istio}, {"linkerd", cmd_linkerd},');
e14.push('    /* Batch 14: AI/ML */');
e14.push('    {"tensorflow", cmd_tensorflow}, {"pytorch", cmd_pytorch}, {"jupyter", cmd_jupyter},');
e14.push('    {"scipy", cmd_scipy}, {"numpy", cmd_numpy}, {"pandas", cmd_pandas},');
e14.push('    {"matplotlib", cmd_matplotlib}, {"sklearn", cmd_sklearn}, {"openai", cmd_openai}, {"ollama", cmd_ollama},');
e14.push('    /* Batch 14: Modern CLI */');
e14.push('    {"tldr", cmd_tldr}, {"exa", cmd_exa}, {"bat", cmd_bat}, {"fzf", cmd_fzf},');
e14.push('    {"rg", cmd_ripgrep}, {"fd", cmd_fd}, {"dust", cmd_dust}, {"duf", cmd_duuf},');
e14.push('    {"httpie", cmd_httpie}, {"yq", cmd_yq}, {"tokei", cmd_tokei}, {"cloc", cmd_cloc},');
e14.push('    /* Batch 14: Load Testing */');
e14.push('    {"hey", cmd_hey}, {"wrk", cmd_wrk}, {"ab", cmd_ab}, {"vegeta", cmd_vegeta},');
e14.push('    {"k6", cmd_k6}, {"locust", cmd_locust}, {"artillery", cmd_artillery}, {"siege", cmd_siege},');
e14.push('    {"jmeter", cmd_jmeter}, {"gatling", cmd_gatling},');

lines.splice(newEnd, 0, ...e14);
fs.writeFileSync(shell, lines.join('\n'), 'utf8');
console.log('Batch 14 applied! Lines:', lines.length);
