const fs = require('fs');
const shell = 'E:/aisystem/byo-os/kernel/shell.c';
let c = fs.readFileSync(shell, 'utf8');
let lines = c.split('\n');
const tableIdx = lines.findIndex(l => l.includes('static const cmd_entry commands[]'));
let endIdx = -1;
for (let i = tableIdx; i < lines.length; i++) { if (lines[i].includes('{0, 0}')) { endIdx = i; break; } }

const b13 = [];
const f = (s) => b13.push(s);

// B13: Desktop Environment
f('/* BATCH 13: Desktop Environment */');
f('static void cmd_xorg(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("X.Org X Server 1.21.0\\n");');
f('}');
f('');
f('static void cmd_xinit(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("xinit: starting X server\\n");');
f('}');
f('');
f('static void cmd_startx(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Starting X Window System\\n");');
f('}');
f('');
f('static void cmd_xrandr(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Screen 0: 1024x768\\nHDMI-1: 1920x1080\\n");');
f('}');
f('');
f('static void cmd_xdg_open(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: xdg-open <file>\\n"); return; }');
f('    vga_puts("Opening: "); vga_puts(args[1]); vga_puts("\\n");');
f('}');
f('');
f('static void cmd_xterm(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("xterm: terminal emulator\\n");');
f('}');
f('');
f('static void cmd_gnome_terminal(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("GNOME Terminal 3.44.0\\n");');
f('}');
f('');
f('static void cmd_bash(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("GNU bash, version 5.2.0\\n");');
f('}');
f('');
f('static void cmd_zsh(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("zsh 5.9\\n");');
f('}');
f('');
f('static void cmd_fish(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("fish, version 3.6.0\\n");');
f('}');
f('');
f('static void cmd_dash(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("dash 0.5.11.5\\n");');
f('}');
f('');
f('static void cmd_csh(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("tcsh 6.24.0\\n");');
f('}');
f('');
// B13: Window Manager
f('/* BATCH 13: Window Manager */');
f('static void cmd_i3(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("i3: tiling window manager\\n");');
f('}');
f('');
f('static void cmd_openbox(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Openbox: stacking window manager\\n");');
f('}');
f('');
f('static void cmd_fluxbox(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Fluxbox: window manager\\n");');
f('}');
f('');
f('static void cmd_sway(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Sway: i3-compatible Wayland compositor\\n");');
f('}');
f('');
// B13: File Manager
f('/* BATCH 13: File Manager */');
f('static void cmd_nemo(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Nemo: file manager\\n");');
f('}');
f('');
f('static void cmd_thunar(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Thunar: file manager\\n");');
f('}');
f('');
f('static void cmd_pcafm(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("PCManFM: file manager\\n");');
f('}');
f('');
// B13: Text Editor GUI
f('/* BATCH 13: GUI Apps */');
f('static void cmd_gedit(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("gedit: text editor\\n");');
f('}');
f('');
f('static void cmd_kate(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Kate: text editor\\n");');
f('}');
f('');
f('static void cmd_mousepad(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Mousepad: text editor\\n");');
f('}');
f('');
// B13: Browser
f('/* BATCH 13: Browser */');
f('static void cmd_firefox(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Firefox 120.0\\n");');
f('}');
f('');
f('static void cmd_chromium(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Chromium 119.0\\n");');
f('}');
f('');
f('static void cmd_w3m(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: w3m <url>\\n"); return; }');
f('    vga_puts("w3m: text browser\\nLoading: "); vga_puts(args[1]); vga_puts("\\n");');
f('}');
f('');
f('static void cmd_links(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: links <url>\\n"); return; }');
f('    vga_puts("Links: text browser\\n");');
f('}');
f('');
f('static void cmd_elinks(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ELinks: text browser\\n");');
f('}');
f('');
// B13: Audio
f('/* BATCH 13: Audio Advanced */');
f('static void cmd_pulseaudio(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("PulseAudio 16.1\\n");');
f('}');
f('');
f('static void cmd_pipewire(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("PipeWire 0.3.0\\n");');
f('}');
f('');
f('static void cmd_aplay(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: aplay <file>\\n"); return; }');
f('    vga_puts("Playing: "); vga_puts(args[1]); vga_puts("\\n");');
f('}');
f('');
f('static void cmd_arecord(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Recording... Ctrl+C to stop\\n");');
f('}');
f('');
f('static void cmd_sox(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("SoX: Swiss Army knife of audio\\n");');
f('}');
f('');
// B13: Video
f('/* BATCH 13: Video Advanced */');
f('static void cmd_vlc(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("VLC media player 3.0.18\\n");');
f('}');
f('');
f('static void cmd_mpv(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: mpv <file>\\n"); return; }');
f('    vga_puts("mpv: "); vga_puts(args[1]); vga_puts("\\n");');
f('}');
f('');
f('static void cmd_xdpyinfo(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("X display: :0\\nDimensions: 1024x768\\n");');
f('}');
f('');
// B13: Printing
f('/* BATCH 13: Printing Advanced */');
f('static void cmd_lpoptions(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("lpoptions: printer options\\n");');
f('}');
f('');
f('static void cmd_lpadmin(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("lpadmin: printer administration\\n");');
f('}');
f('');
f('static void cmd_cancel(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("cancel: job cancelled\\n");');
f('}');
f('');
f('static void cmd_lp(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: lp <file>\\n"); return; }');
f('    vga_puts("lp: job queued\\n");');
f('}');
f('');
// B13: Internationalization
f('/* BATCH 13: i18n */');
f('static void cmd_localectl_imp(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("System Locale: en_US.UTF-8\\nVC Keymap: us\\n");');
f('}');
f('');
f('static void cmd_iconv(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("iconv: character set conversion\\n");');
f('}');
f('');
f('static void cmd_locale(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("LANG=en_US.UTF-8\\nLC_CTYPE=en_US.UTF-8\\nLC_ALL=en_US.UTF-8\\n");');
f('}');
f('');
f('static void cmd_gettext(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("gettext: internationalization\\n");');
f('}');
f('');
f('static void cmd_env_imp(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("PATH=/usr/bin:/bin\\nHOME=/root\\nSHELL=/bin/bash\\nLANG=en_US.UTF-8\\n");');
f('}');
f('');
// B13: Timezone
f('/* BATCH 13: Timezone */');
f('static void cmd_tzselect(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Timezone: UTC\\n");');
f('}');
f('');
f('static void cmd_timedatectl_imp(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Local time: 2025-01-15 12:00:00 UTC\\nNTP: active\\n");');
f('}');
f('');
// B13: Systemd
f('/* BATCH 13: Systemd Advanced */');
f('static void cmd_journalctl_imp2(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Logs begin at boot.\\nJan 15 12:00:00 byo-os kernel: BYO-OS 1.0\\n");');
f('}');
f('');
f('static void cmd_systemctl_imp(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: systemctl [start|stop|status|enable|disable] <unit>\\n"); return; }');
f('    vga_puts(args[1]); vga_puts(": operation completed\\n");');
f('}');
f('');
f('static void cmd_systemd_run(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("systemd-run: transient unit created\\n");');
f('}');
f('');
f('static void cmd_machinectl(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("machinectl: container/machine manager\\n");');
f('}');
f('');
f('static void cmd_networkd(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("systemd-networkd: network management\\n");');
f('}');
f('');
f('static void cmd_resolved(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("systemd-resolved: DNS stub resolver\\n");');
f('}');
f('');
f('static void cmd_timesyncd(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("systemd-timesyncd: NTP synchronization\\n");');
f('}');
f('');
// B13: Snap/Flatpak/Brew
f('/* BATCH 13: Package Managers Extended */');
f('static void cmd_brew(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Homebrew 4.1.0\\n");');
f('}');
f('');
f('static void cmd_pacman(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: pacman [-S|-R|-Q] <pkg>\\n"); return; }');
f('    vga_puts("pacman: operation completed\\n");');
f('}');
f('');
f('static void cmd_emerge(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("emerge: Gentoo package manager\\n");');
f('}');
f('');
f('static void cmd_apk(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: apk [add|del|list] <pkg>\\n"); return; }');
f('    vga_puts("apk: operation completed\\n");');
f('}');
f('');
f('static void cmd_zypper(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("zypper: openSUSE package manager\\n");');
f('}');
f('');
// B13: Container orchestration
f('/* BATCH 13: Container Orchestration */');
f('static void cmd_kubectl(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: kubectl [get|create|delete|apply] <resource>\\n"); return; }');
f('    if (strcmp(args[1], "get") == 0) {');
f('        vga_puts("NAME    STATUS  AGE\\npod-1   Running 1d\\n");');
f('    } else { vga_puts("kubectl: operation completed\\n"); }');
f('}');
f('');
f('static void cmd_helm(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Helm 3.12.0\\n");');
f('}');
f('');
f('static void cmd_compose(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: docker-compose [up|down|ps]\\n"); return; }');
f('    vga_puts("docker-compose: operation completed\\n");');
f('}');
f('');
// B13: CI/CD
f('/* BATCH 13: CI/CD */');
f('static void cmd_jenkins(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Jenkins: automation server\\n");');
f('}');
f('');
f('static void cmd_gitlab_ci(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("GitLab CI: pipeline runner\\n");');
f('}');
f('');
f('static void cmd_github_actions(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("GitHub Actions: workflow runner\\n");');
f('}');
f('');
// B13: Cloud tools
f('/* BATCH 13: Cloud */');
f('static void cmd_aws(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("aws-cli 2.15.0\\n");');
f('}');
f('');
f('static void cmd_azure(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("azure-cli 2.55.0\\n");');
f('}');
f('');
f('static void cmd_gcloud(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("gcloud 456.0.0\\n");');
f('}');
f('');
f('static void cmd_terraform(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Terraform 1.6.0\\n");');
f('}');
f('');
f('static void cmd_ansible(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ansible 2.15.0\\n");');
f('}');
f('');
f('static void cmd_puppet(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Puppet 8.5.0\\n");');
f('}');
f('');
f('static void cmd_chef(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Chef Infra Client 18.2.0\\n");');
f('}');
f('');
// B13: Monitoring
f('/* BATCH 13: Monitoring Advanced */');
f('static void cmd_htop(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("htop 3.2.0 - process viewer\\n");');
f('}');
f('');
f('static void cmd_atop(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("atop: system monitor\\n");');
f('}');
f('');
f('static void cmd_glances(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Glances: system monitoring\\n");');
f('}');
f('');
f('static void cmd_dstat(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("dstat: resource statistics\\n");');
f('}');
f('');
f('static void cmd_nethogs(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("nethogs: bandwidth monitor\\n");');
f('}');
f('');
f('static void cmd_iftop(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("iftop: network bandwidth\\n");');
f('}');
f('');
f('static void cmd_bandwhich(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("bandwhich: bandwidth monitor\\n");');
f('}');
f('');
// B13: System info
f('/* BATCH 13: System Info Advanced */');
f('static void cmd_fastfetch(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("BYO-OS 1.0\\nKernel: BYO 1.0\\nShell: byo-shell\\nTerminal: VGA\\n");');
f('}');
f('');
f('static void cmd_screenfetch(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("BYO-OS 1.0\\nKernel: BYO 1.0\\nUptime: 0 days\\n");');
f('}');
f('');
f('static void cmd_pfetch(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("BYO-OS\\nKernel: BYO 1.0\\n");');
f('}');
f('');
f('static void cmd_uname_imp(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc >= 2 && strcmp(args[1], "-a") == 0) {');
f('        vga_puts("BYO-OS byo-os 1.0.0 #1 SMP x86_64 GNU/BYO\\n");');
f('    } else {');
f('        vga_puts("BYO-OS\\n");');
f('    }');
f('}');
f('');
// B13: Network advanced
f('/* BATCH 13: Network Advanced */');
f('static void cmd_ip(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: ip [addr|link|route] [show|add|del]\\n"); return; }');
f('    if (strcmp(args[1], "addr") == 0) {');
f('        vga_puts("1: lo: <LOOPBACK> inet 127.0.0.1/8\\n2: eth0: <BROADCAST> inet 192.168.1.100/24\\n");');
f('    } else if (strcmp(args[1], "link") == 0) {');
f('        vga_puts("1: lo: <LOOPBACK> mtu 65536\\n2: eth0: <BROADCAST> mtu 1500\\n");');
f('    } else if (strcmp(args[1], "route") == 0) {');
f('        vga_puts("default via 192.168.1.1 dev eth0\\n192.168.1.0/24 dev eth0\\n");');
f('    } else {');
f('        vga_puts("ip: operation completed\\n");');
f('    }');
f('}');
f('');
f('static void cmd_ip6(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("1: lo: inet6 ::1/128\\n2: eth0: inet6 fe80::1/64\\n");');
f('}');
f('');
f('static void cmd_brctl(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("bridge: br0\\ninterfaces: eth0\\n");');
f('}');
f('');
f('static void cmd_vconfig(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("vconfig: VLAN configuration\\n");');
f('}');
f('');
f('static void cmd_tunctl(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("tunctl: TUN/TAP configuration\\n");');
f('');
f('');
f('static void cmd_socat(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("socat: bidirectional data relay\\n");');
f('}');
f('');
f('static void cmd_ncat(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ncat: netcat reimplementation\\n");');
f('}');
f('');
f('static void cmd_netcat(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("netcat: TCP/UDP connections\\n");');
f('}');
f('');
f('static void cmd_whois(int argc, char args[][CMD_MAX_LEN]) {');
f('    if (argc < 2) { vga_puts("Usage: whois <domain>\\n"); return; }');
f('    vga_puts(args[1]); vga_puts(": domain info\\nRegistrar: BYO\\n");');
f('}');

// Insert functions before table
lines.splice(tableIdx, 0, ...b13);

// Find new end
let newEnd = -1;
for (let i = tableIdx + b13.length; i < lines.length; i++) { if (lines[i].includes('{0, 0}')) { newEnd = i; break; } }

// Table entries
const e13 = [];
e13.push('    /* Batch 13: Desktop */');
e13.push('    {"xorg", cmd_xorg}, {"xinit", cmd_xinit}, {"startx", cmd_startx}, {"xrandr", cmd_xrandr},');
e13.push('    {"xdg-open", cmd_xdg_open}, {"xterm", cmd_xterm}, {"gnome-terminal", cmd_gnome_terminal},');
e13.push('    {"bash", cmd_bash}, {"zsh", cmd_zsh}, {"fish", cmd_fish}, {"dash", cmd_dash}, {"csh", cmd_csh},');
e13.push('    {"i3", cmd_i3}, {"openbox", cmd_openbox}, {"sway", cmd_sway},');
e13.push('    {"firefox", cmd_firefox}, {"chromium", cmd_chromium}, {"w3m", cmd_w3m}, {"links", cmd_links}, {"elinks", cmd_elinks},');
e13.push('    {"gedit", cmd_gedit}, {"kate", cmd_kate}, {"mousepad", cmd_mousepad},');
e13.push('    {"nemo", cmd_nemo}, {"thunar", cmd_thunar}, {"pcmanfm", cmd_pcafm},');
e13.push('    {"xdpyinfo", cmd_xdpyinfo},');
e13.push('    /* Batch 13: Audio/Video */');
e13.push('    {"pulseaudio", cmd_pulseaudio}, {"pipewire", cmd_pipewire},');
e13.push('    {"aplay", cmd_aplay}, {"arecord", cmd_arecord}, {"sox", cmd_sox},');
e13.push('    {"vlc", cmd_vlc}, {"mpv", cmd_mpv},');
e13.push('    /* Batch 13: Print */');
e13.push('    {"lpoptions", cmd_lpoptions}, {"lpadmin", cmd_lpadmin}, {"cancel", cmd_cancel}, {"lp", cmd_lp},');
e13.push('    /* Batch 13: i18n */');
e13.push('    {"locale", cmd_locale}, {"iconv", cmd_iconv}, {"gettext", cmd_gettext}, {"tzselect", cmd_tzselect},');
e13.push('    /* Batch 13: Systemd */');
e13.push('    {"systemd-run", cmd_systemd_run}, {"machinectl", cmd_machinectl},');
e13.push('    {"networkd", cmd_networkd}, {"resolved", cmd_resolved}, {"timesyncd", cmd_timesyncd},');
e13.push('    /* Batch 13: Package Extended */');
e13.push('    {"brew", cmd_brew}, {"pacman", cmd_pacman}, {"emerge", cmd_emerge}, {"apk", cmd_apk}, {"zypper", cmd_zypper},');
e13.push('    /* Batch 13: Containers Orch */');
e13.push('    {"kubectl", cmd_kubectl}, {"helm", cmd_helm}, {"docker-compose", cmd_compose},');
e13.push('    /* Batch 13: CI/CD */');
e13.push('    {"jenkins", cmd_jenkins}, {"gitlab-ci", cmd_gitlab_ci}, {"github-actions", cmd_github_actions},');
e13.push('    /* Batch 13: Cloud */');
e13.push('    {"aws", cmd_aws}, {"az", cmd_azure}, {"gcloud", cmd_gcloud},');
e13.push('    {"terraform", cmd_terraform}, {"ansible", cmd_ansible}, {"puppet", cmd_puppet}, {"chef", cmd_chef},');
e13.push('    /* Batch 13: Monitor */');
e13.push('    {"htop", cmd_htop}, {"atop", cmd_atop}, {"glances", cmd_glances}, {"dstat", cmd_dstat},');
e13.push('    {"nethogs", cmd_nethogs}, {"iftop", cmd_iftop}, {"bandwhich", cmd_bandwhich},');
e13.push('    /* Batch 13: System Info */');
e13.push('    {"fastfetch", cmd_fastfetch}, {"screenfetch", cmd_screenfetch}, {"pfetch", cmd_pfetch},');
e13.push('    /* Batch 13: Network Advanced */');
e13.push('    {"ip", cmd_ip}, {"ip6", cmd_ip6}, {"brctl", cmd_brctl},');
e13.push('    {"socat", cmd_socat}, {"ncat", cmd_ncat}, {"netcat", cmd_netcat}, {"whois", cmd_whois},');

lines.splice(newEnd, 0, ...e13);
fs.writeFileSync(shell, lines.join('\n'), 'utf8');
console.log('Batch 13 applied! Lines:', lines.length);
