const fs = require('fs');
const shell = 'E:/aisystem/byo-os/kernel/shell.c';
let c = fs.readFileSync(shell, 'utf8');
let lines = c.split('\n');
const tableIdx = lines.findIndex(l => l.includes('static const cmd_entry commands[]'));
let endIdx = -1;
for (let i = tableIdx; i < lines.length; i++) { if (lines[i].includes('{0, 0}')) { endIdx = i; break; } }

const b16 = [];
const f = (s) => b16.push(s);

// B16: Game/Entertainment
f('/* BATCH 16: Game/Entertainment */');
f('static void cmd_steam(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Steam: gaming platform\\n");');
f('}');
f('');
f('static void cmd_wine(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Wine: Windows compatibility\\n");');
f('}');
f('');
f('static void cmd_proton(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Proton: Steam Play\\n");');
f('}');
f('');
f('static void cmd_lutris(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Lutris: game manager\\n");');
f('}');
f('');
f('static void cmd_dosbox(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("DOSBox: DOS emulator\\n");');
f('}');
f('');
f('static void cmd_retroarch(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("RetroArch: retro gaming\\n");');
f('}');
f('');
// B16: Graphics
f('/* BATCH 16: Graphics */');
f('static void cmd_gimp(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("GIMP 2.10: image editor\\n");');
f('}');
f('');
f('static void cmd_inkscape(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Inkscape 1.3: vector graphics\\n");');
f('}');
f('');
f('static void cmd_blender(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Blender 4.0: 3D creation\\n");');
f('}');
f('');
f('static void cmd_imagemagick(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ImageMagick 7.1\\n");');
f('}');
f('');
f('static void cmd_darktable(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("darktable: photo workflow\\n");');
f('}');
f('');
f('static void cmd_rawtherapee(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("RawTherapee: raw photo editor\\n");');
f('}');
f('');
f('static void cmd_krita(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Krita: digital painting\\n");');
f('}');
f('');
f('static void cmd_scribus(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Scribus: desktop publishing\\n");');
f('}');
f('');
// B16: Office
f('/* BATCH 16: Office */');
f('static void cmd_libreoffice(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("LibreOffice 7.6\\n");');
f('}');
f('');
f('static void cmd_pandoc(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Pandoc 3.0: document converter\\n");');
f('}');
f('');
f('static void cmd_tesseract(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Tesseract: OCR engine\\n");');
f('}');
f('');
f('static void cmd_poppler(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Poppler: PDF utilities\\n");');
f('}');
f('');
f('static void cmd_ghostscript(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Ghostscript: PostScript interpreter\\n");');
f('}');
f('');
f('static void cmd_wkhtmltopdf(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("wkhtmltopdf: HTML to PDF\\n");');
f('}');
f('');
// B16: Communication
f('/* BATCH 16: Communication */');
f('static void cmd_element(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Element: Matrix client\\n");');
f('}');
f('');
f('static void cmd_signal(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Signal: encrypted messenger\\n");');
f('}');
f('');
f('static void cmd.telegram(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Telegram: messaging\\n");');
f('}');
f('');
f('static void cmd_discord(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Discord: voice/text chat\\n");');
f('}');
f('');
f('static void cmd_slack(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Slack: team messaging\\n");');
f('}');
f('');
f('static void cmd_teams(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Microsoft Teams\\n");');
f('}');
f('');
f('static void cmd_zoom(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Zoom: video conferencing\\n");');
f('}');
f('');
f('static void cmd_mattermost(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Mattermost: team messaging\\n");');
f('}');
f('');
f('static void cmd_rocket_chat(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Rocket.Chat: team messaging\\n");');
f('}');
f('');
f('static void cmd_zulip(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Zulip: team messaging\\n");');
f('}');
f('');
// B16: VPN/Proxy
f('/* BATCH 16: VPN/Proxy */');
f('static void cmd_wireguard(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("WireGuard: modern VPN\\n");');
f('}');
f('');
f('static void cmd_ipsec(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("IPSec: VPN protocol\\n");');
f('}');
f('');
f('static void cmd_l2tp(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("L2TP: Layer 2 tunneling\\n");');
f('}');
f('');
f('static void cmd_pptp(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("PPTP: Point-to-Point tunneling\\n");');
f('}');
f('');
f('static void cmd_shadowsocks(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ShadowSocks: proxy\\n");');
f('}');
f('');
f('static void cmd_v2ray(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("V2Ray: proxy platform\\n");');
f('}');
f('');
f('static void cmd_xray(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Xray: proxy platform\\n");');
f('}');
f('');
f('static void cmd_trojan(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Trojan: proxy protocol\\n");');
f('}');
f('');
f('static void cmd_hysteria(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Hysteria: proxy protocol\\n");');
f('}');
f('');
// B16: DNS Extended
f('/* BATCH 16: DNS Extended */');
f('static void cmd_powerdns(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("PowerDNS: authoritative DNS\\n");');
f('}');
f('');
f('static void cmd_coredns(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("CoreDNS: DNS server\\n");');
f('}');
f('');
f('static void cmd_blocky(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Blocky: DNS proxy/blocker\\n");');
f('}');
f('');
f('static void cmd_pihole(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Pi-hole: DNS sinkhole\\n");');
f('}');
f('');
// B16: IoT/Edge
f('/* BATCH 16: IoT/Edge */');
f('static void cmd_mosquitto(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Mosquitto: MQTT broker\\n");');
f('}');
f('');
f('static void cmd_emqx(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("EMQX: MQTT broker\\n");');
f('}');
f('');
f('static void cmd_homeassistant(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Home Assistant: home automation\\n");');
f('}');
f('');
f('static void cmd_node_red(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Node-RED: flow automation\\n");');
f('}');
f('');
f('static void cmdgrafana_on(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Grafana OnCall: incident management\\n");');
f('}');
f('');
// B16: Database Extended
f('/* BATCH 16: Database Extended */');
f('static void cmd_timescaledb(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("TimescaleDB: time-series\\n");');
f('}');
f('');
f('static void cmd_yugabytedb(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("YugabyteDB: distributed SQL\\n");');
f('}');
f('');
f('static void cmd_cockroachdb(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("CockroachDB: distributed SQL\\n");');
f('}');
f('');
f('static void cmd_planetscale(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("PlanetScale: serverless MySQL\\n");');
f('}');
f('');
f('static void cmd_supabase(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Supabase: open source Firebase\\n");');
f('}');
f('');
f('static void cmd_appwrite(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Appwrite: backend server\\n");');
f('}');
f('');
f('static void cmd_pocketbase(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("PocketBase: backend in 1 file\\n");');
f('}');
f('');
f('static void cmd_nhost(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Nhost: open source Firebase\\n");');
f('}');
f('');
// B16: Misc
f('/* BATCH 16: Misc Extended */');
f('static void cmd_openzfs(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("OpenZFS: filesystem\\n");');
f('}');
f('');
f('static void cmd_btrfs(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Btrfs: filesystem\\n");');
f('}');
f('');
f('static void cmd_zfs(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ZFS: filesystem\\n");');
f('}');
f('');
f('static void cmd_xfs(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("XFS: filesystem\\n");');
f('}');
f('');
f('static void cmd_bcache(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("bcache: block cache\\n");');
f('}');
f('');
f('static void cmd_dracut(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("dracut: initramfs generator\\n");');
f('}');
f('');
f('static void cmd_mkinitcpio(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("mkinitcpio: initramfs generator\\n");');
f('}');
f('');
f('static void cmd_grub(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("GRUB: bootloader\\n");');
f('}');
f('');
f('static void cmd_systemd_boot(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("systemd-boot: bootloader\\n");');
f('}');
f('');
f('static void cmd_refind(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("rEFInd: bootloader\\n");');
f('}');
f('');
f('static void cmd_limine(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Limine: bootloader\\n");');
f('}');
f('');
f('static void cmd_memtest86(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Memtest86: memory test\\n");');
f('}');
f('');
f('static void cmd_stress(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("stress: system stress test\\n");');
f('}');
f('');
f('static void cmd_sysbench(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("sysbench: system benchmark\\n");');
f('}');
f('');
f('static void cmd_fio(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("fio: flexible I/O tester\\n");');
f('}');
f('');
f('static void cmd_iozone(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("iozone: filesystem benchmark\\n");');
f('}');
f('');
f('static void cmd_hdparm(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("hdparm: disk parameter\\n");');
f('}');
f('');
f('static void cmd_smartctl(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("smartctl: SMART monitoring\\n");');
f('}');
f('');
f('static void cmd_nvme(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("nvme: NVMe management\\n");');
f('}');
f('');
f('static void cmd_megacli(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("MegaCLI: RAID controller\\n");');
f('}');
f('');
f('static void cmd_ssacli(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ssacli: Smart Storage Administrator\\n");');
f('}');
f('');
f('static void cmd_ipmitool(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("ipmitool: BMC management\\n");');
f('}');
f('');
f('static void cmd_dmidecode(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("dmidecode: DMI table decoder\\n");');
f('}');
f('');
f('static void cmd_lldpd(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("lldpd: LLDP daemon\\n");');
f('}');
f('');
f('static void cmd_bird(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("BIRD: routing daemon\\n");');
f('}');
f('');
f('static void cmd_frrouting(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("FRRouting: routing suite\\n");');
f('}');
f('');
f('static void cmd_quagga(int argc, char args[][CMD_MAX_LEN]) {');
f('    vga_puts("Quagga: routing daemon\\n");');
f('}');

// Insert functions before table
lines.splice(tableIdx, 0, ...b16);

// Find new end
let newEnd = -1;
for (let i = tableIdx + b16.length; i < lines.length; i++) { if (lines[i].includes('{0, 0}')) { newEnd = i; break; } }

// Table entries
const e16 = [];
e16.push('    /* Batch 16: Game */');
e16.push('    {"steam", cmd_steam}, {"wine", cmd_wine}, {"proton", cmd_proton}, {"lutris", cmd_lutris},');
e16.push('    {"dosbox", cmd_dosbox}, {"retroarch", cmd_retroarch},');
e16.push('    /* Batch 16: Graphics */');
e16.push('    {"gimp", cmd_gimp}, {"inkscape", cmd_inkscape}, {"blender", cmd_blender},');
e16.push('    {"imagemagick", cmd_imagemagick}, {"darktable", cmd_darktable}, {"krita", cmd_krita}, {"scribus", cmd_scribus},');
e16.push('    /* Batch 16: Office */');
e16.push('    {"libreoffice", cmd_libreoffice}, {"pandoc", cmd_pandoc}, {"tesseract", cmd_tesseract},');
e16.push('    {"poppler", cmd_poppler}, {"ghostscript", cmd_ghostscript}, {"wkhtmltopdf", cmd_wkhtmltopdf},');
e16.push('    /* Batch 16: Communication */');
e16.push('    {"element", cmd_element}, {"signal", cmd_signal}, {"discord", cmd_discord},');
e16.push('    {"slack", cmd_slack}, {"teams", cmd_teams}, {"zoom", cmd_zoom},');
e16.push('    {"mattermost", cmd_mattermost}, {"rocketchat", cmd_rocket_chat}, {"zulip", cmd_zulip},');
e16.push('    /* Batch 16: VPN */');
e16.push('    {"wireguard", cmd_wireguard}, {"ipsec", cmd_ipsec}, {"shadowsocks", cmd_shadowsocks},');
e16.push('    {"v2ray", cmd_v2ray}, {"xray", cmd_xray}, {"trojan", cmd_trojan}, {"hysteria", cmd_hysteria},');
e16.push('    /* Batch 16: DNS Extended */');
e16.push('    {"powerdns", cmd_powerdns}, {"coredns", cmd_coredns}, {"pihole", cmd_pihole}, {"blocky", cmd_blocky},');
e16.push('    /* Batch 16: IoT */');
e16.push('    {"mosquitto", cmd_mosquitto}, {"emqx", cmd_emqx},');
e16.push('    {"homeassistant", cmd_homeassistant}, {"node-red", cmd_node_red},');
e16.push('    /* Batch 16: Database Extended */');
e16.push('    {"timescaledb", cmd_timescaledb}, {"cockroachdb", cmd_cockroachdb},');
e16.push('    {"supabase", cmd_supabase}, {"appwrite", cmd_appwrite}, {"pocketbase", cmd_pocketbase},');
e16.push('    /* Batch 16: Filesystem */');
e16.push('    {"openzfs", cmd_openzfs}, {"btrfs", cmd_btrfs}, {"zfs", cmd_zfs}, {"xfs", cmd_xfs},');
e16.push('    /* Batch 16: Boot */');
e16.push('    {"grub", cmd_grub}, {"systemd-boot", cmd_systemd_boot}, {"refind", cmd_refind}, {"limine", cmd_limine},');
e16.push('    {"dracut", cmd_dracut}, {"mkinitcpio", cmd_mkinitcpio},');
e16.push('    /* Batch 16: Benchmark */');
e16.push('    {"memtest86", cmd_memtest86}, {"stress", cmd_stress}, {"sysbench", cmd_sysbench},');
e16.push('    {"fio", cmd_fio}, {"iozone", cmd_iozone},');
e16.push('    /* Batch 16: Hardware */');
e16.push('    {"hdparm", cmd_hdparm}, {"smartctl", cmd_smartctl}, {"nvme", cmd_nvme},');
e16.push('    {"dmidecode", cmd_dmidecode}, {"ipmitool", cmd_ipmitool},');
e16.push('    /* Batch 16: Routing */');
e16.push('    {"lldpd", cmd_lldpd}, {"bird", cmd_bird}, {"frr", cmd_frrouting}, {"quagga", cmd_quagga},');

lines.splice(newEnd, 0, ...e16);
fs.writeFileSync(shell, lines.join('\n'), 'utf8');
console.log('Batch 16 applied! Lines:', lines.length);
